### PR TITLE
Panthor dependency update

### PR DESCRIPTION
**Pull request by Nilithus**
This PR simply bumps dependency versions and fixes any unit tests or namespaces that broke from that. 

It sets the stage for making bigger changes around symfony 4.0 components like auto setting route services to public, auto configuring twig templates for controllers, and anything else that would go into a new release.

### CODE REVIEW

**Comment by Nilithus** [comment]
Will need to update CircleCI, drop php5.6 and add php7.2 as well as install sodium 2.0

**Comment by Nilithus** [comment]
Add a few more things to this PR to move it along towards implementing a base of things wanted for panthor 3.2

- I added a panthor compiler pass that marks all `ControllerInterface::class` and `MiddlewareInterface::class` as public in the container.
- I removed use of `libsodium` in the encryption class now only `sodium` is allowed.
    - It now does a simple `extension_loaded('sodium')` check in the constructor and errors out if it doesn't exist
- Required php version is bumped to `^7.1.3` symfony ~4.0 components drop support for `7.0`

The compiler pass would be easy to extend to also do the `twig` template tagging we've talked about at work. Anyway I just need to fix the php7.1 docker image to install the sodium extension then those tests should be all good. I'll clean up the history too so it's not so messy with bug fixes.

@skluck BTW if you don't want me doing this or are already doing this yourself let me know and I'll work on other things.

**Comment by skluck** [comment]
I will get this in before next week, combined with my small changes in [next](https://github.com/quickenloans-mcp/mcp-panthor/tree/next).

Sorry, my oss has been mostly focused on making the skill survey into a full blown [vue app](https://github.com/skluck/skill-survey/tree/development/src).

**Comment by skluck** [comment]
Changed merged as of 62eea0ad118c6a6b3c2e09a36abb0803060f761f

**Pull request closed without merging**
